version: '3'

services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'
    volumes:
      - ./var/db:/var/lib/mysql
  gotenberg:
    network_mode: "host"
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
